config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[show index]

  root 'rooms#index'

  patch '/user_tasks/:id', to: 'user_tasks#update', as: 'user_task'

  resources :rooms do
    resources :tasks, shallow: true do
      post '/user_tasks', to: 'user_tasks#create', as: 'volunteer'
      get '/user_tasks', to: 'user_tasks#new', as: 'help'
      delete '/user_tasks', to: 'user_tasks#destroy', as: 'cancel'
    end
  end

  get '/users/:id/tasks', to: 'tasks#index', as: 'users_tasks'
  get '/needs_help', to: 'needs_help#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :room
  delegate :user, to: :room
  has_many :user_tasks, dependent: :destroy
  has_many :helpers, through: :user_tasks, source: :user
  scope :needs_help, -> { where(needs_help: true) }

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_room, except: %i[update destroy]
  before_action :set_task, only: %i[edit update destroy show]

  def index
    # binding.pry
    if params[:id]
      user = User.find_by(id: params[:id])
      @tasks = user.tasks
    @usertasks = @tasks.map { |task| task.user_tasks }.flatten

    else 
    @tasks = @room.tasks
    @usertasks = @tasks.map { |task| task.user_tasks }.flatten
    end 
  end

  def new
    @task = @room.tasks.build
  end

  def create
    @task = @room.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to room_path(@room), notice: 'Task was successfully created!' }
        format.json { render room_path(@room), status: :created, location: @task }
      else
        format.html { render :new }
   end
    end
  end

  def edit; end

  def update
    if params[:task]
      if @task.update(task_params)
        @room = Room.find_by(id: @task[:room_id]) if params[:task]
        redirect_to room_path(@room), notice: 'Task was successfully updated.'
      else
        render :edit
        end

    else
      get_room
      @task.update(needs_help: !@task.needs_help)
      redirect_to root_path, notice: 'Good job asking for help!'

  end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to room_path(@task.room), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show; end

  private

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def get_room
    @room = Room.find_by(id: params[:room_id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @task}  %>


<%= form_for [@room, @task] do |f| %>


<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<div class='actions'>
  <%= f.submit %>
</div>

<% end %>

app/views/tasks/_help_signup.html.erb
<div id='header'>
  <h4> Signed up to Help: </h4>
</div>
<div id="container">
  <% if !@room %>
  <table>
    <tr>
      <th> Name </th>
      <th> Description </th>
      <th> Person's Contact </th>
      <th> Cancel</th>
      <th> Instructions </th>


    </tr>
    <% current_user.helped_tasks.each do |t| %>
    <tr>
      <td> <%= t.name %> </td>
      <td> <%= t.description %></td>
      <td> <%= t.user.email %></td>
      <td> <%= link_to "Can't make it", task_cancel_path(t), method: :delete %></td>
      <td>

        <%= t.user_tasks.find_by(task_id: t.id).instructions? ?  t.user_tasks.find_by(task_id: t.id).instructions : "N/A" %>



      </td>



    </tr>
    <% end %>
  </table>
  <%end%>
</div>

app/views/tasks/_helping_list.html.erb
<% if current_user.helpers.count > 0 %>
<div id='header'>
  <h4>Helping Me:</h4>
</div>
<% @tasks.each do |task| %>
<% task.helpers.each.with_index do |helper, i| %>
<div class='card'>

  <h4><%= task.name %></h4>
  <p><%= helper.first_name %>
    <%= helper.last_name %></p>
  <p><%= helper.email %></p>
  <%= form_with model: @usertasks[i] do |f| %>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <%= @message %>
  <%= submit_tag('Submit')%>
  <% end %>
</div>

<% end %>
<% end %>
<% end %>

app/views/tasks/_tasks.html.erb
<div id='header'>
  <h4>My Tasks:</h4>
</div>

<div id="container">
  <% if !@tasks %>
  There are no tasks to display
  <% else %>
  <table>
    <tr>

      <th> Room </th>
      <th> Name </th>
      <th> Description </th>
      <th> Edit </th>
      <th> Delete</th>
      <th> Get Help? </th>

    </tr>
    <% @tasks.each do |t| %>
    <tr>


      <td> <%= t.room.name %> </td>
      <td> <%= t.name %> </td>
      <td> <%= t.description %></td>
      <td><%= link_to "Edit", edit_task_path(t)%></td>
      <td><%= link_to "Delete", t , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><% if t.needs_help %>



        <%= link_to "Stop asking for Help", t, method: :patch %>
        <% else %>
        <%= link_to "Get Help", t, method: :patch %>
        <% end %></td>


      <% end %>
    </tr>


  </table>
  <%end %>
</div>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= render 'tasks/form', task: @task %>

app/views/tasks/index.html.erb
<%= render '/tasks/tasks' %>


<%= render '/tasks/helping_list' %>

app/views/tasks/new.html.erb
<h2>Add Task for <%= @task.room.name.capitalize %> </h2>

<%= render 'tasks/form', task: @task %>