config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[show index]

  root 'rooms#index'

  patch '/user_tasks/:id', to: 'user_tasks#update', as: 'user_task'

  resources :rooms do
    resources :tasks, shallow: true do
      post '/user_tasks', to: 'user_tasks#create', as: 'volunteer'
      get '/user_tasks', to: 'user_tasks#new', as: 'help'
      delete '/user_tasks', to: 'user_tasks#destroy', as: 'cancel'
    end
  end

  get '/users/:id/tasks', to: 'tasks#index', as: 'users_tasks'
  get '/needs_help', to: 'needs_help#index'
end

app/controllers/needs_help_controller.rb
class NeedsHelpController < ApplicationController
  before_action :set_tasks
  def index
    if params[:name]
      @search = @tasks.where('name LIKE ?', "%#{params[:name]}%")
    else

      @usertask = UserTask.find_by(id: params[:id])
    end
  end

  private

  def set_tasks
    @tasks = Task.needs_help
  end
end

app/helpers/needs_help_helper.rb
module NeedsHelpHelper
  def date(task); end
end

app/views/needs_help/index.html.erb
<h2>Search for a type of Task</h2>
<%= form_tag({controller: "needs_help"}, method: :get) do %>
Task Incl.: <%= text_field_tag :name %>
<%= submit_tag 'Search' %>
<% end %>

<% if @search %>
<h3> Check out: </h3>
<% @search.each do |task| %>
<p><%= task.name %> : <%= task.description %></p>
<% if task.helpers.exclude?(current_user) %>

<p><%= link_to "Help Out", task_help_path(task), method: :post %></p>
<% else %>
<h5>You've signed up!</h5>
<% end %>
<% end %>
<% end %>

<h1>Community Tasks</h1>
<table>
  <tr>
    <th> Task Name </th>
    <th> Description </th>
    <th> Owner </th>
    <th> Volunteer to Help </th>


  </tr>
  <% @tasks.each do |t| %>

  <tr>
    <% if t.user == current_user %>
    <td> Your task for <%= t.name %> is displayed for others to sign up!</td>
    <% else %>
    <td> <%= t.name %> </td>
    <td> <%= t.description %></td>
    <td> <%= t.user.email %></td>
    <% if t.helpers.exclude?(current_user) %>
    <td><%= link_to "Help Out", task_help_path(t), method: :post %></td>
    <% else %>
    <td> Signed Up! </td>
    <% end %>

  </tr>
  <% end %>
  <% end %>
</table>

app/views/needs_help/new.html.erb
    <p>Need some help for <%= @task.name %> ? </p>
    <p>When do you need it for?</p>

    <%= form_for(@task) do |f| %>
    <%= f.label :finish_by %>
    <%= f.datetime_select :finish_by %>
    <%= f.submit %>


    <%= link_to "Volunteer", task_volunteer_path, method: :post %>
    <td><%= link_to "Volunteer", task_volunteer_path(t), method: :post %></td>