config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[show index]

  root 'rooms#index'

  patch '/user_tasks/:id', to: 'user_tasks#update', as: 'user_task'

  resources :rooms do
    resources :tasks, shallow: true do
      post '/user_tasks', to: 'user_tasks#create', as: 'volunteer'
      get '/user_tasks', to: 'user_tasks#new', as: 'help'
      delete '/user_tasks', to: 'user_tasks#destroy', as: 'cancel'
    end
  end

  get '/users/:id/tasks', to: 'tasks#index', as: 'users_tasks'
  get '/needs_help', to: 'needs_help#index'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :tasks, -> { order('created_at DESC') }, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, :user_room, only: %i[show edit update destroy]
  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
      end
    end
  end

  def index
    @rooms = current_user.rooms
  end

  def show; end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :description, :features)
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def user_room
    redirect_to root_path, notice: 'Sorry, you can not view other user rooms.' if current_user != @room.user
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_count(user)
    user.rooms.count
  end
end

app/views/rooms/edit.html.erb
<h3>Edit Details for <%= @room.name %></h3>

<%= form_for(@room) do |f| %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :features %>
  <%= f.text_field :features %>
</div>

<%= f.submit %>

<% end %>

app/views/rooms/index.html.erb
<div id='header'>
  <h3>Rooms Dashboard</h3>
</div>



<% @rooms.each do |room| %>
<div class='card'>
  <p><%= link_to "#{room.name.capitalize}", room %></p>
</div>
<% end %>


<p><%= link_to 'Add Room', new_room_path %></p>

app/views/rooms/new.html.erb
<h4> Rooms New Page </h4>

<%= render partial: 'layouts/errors', locals: {object: @room}  %>




<%= form_for @room do |f| %>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :features %>
  <%= f.text_field :features %>
</div>

<%= f.submit %>

<% end %>

app/views/rooms/show.html.erb
<h3><%= @room.name.capitalize %> Dashboard </h3>

<h4>Description</h4>
<ul>
  <li><%= @room.description %></li>
</ul>
<h4> Features:</h4>
<ul>
  <li><%= @room.features %></li>
</ul>
<p>
<div>
  <%= link_to "Edit Details", edit_room_path(@room) %> |
  <%= link_to 'Delete Room', room_path(@room), method: :delete %>
</div>
</p>
<h4>Tasks to Do </h4>

<ul>
  <% @room.tasks.each do |t| %>

  <li><%= t.name %> : <%= t.description %></li>



  <% end %>
</ul>

<%= link_to 'Add Task', new_room_task_path(@room) %> |
<%= link_to 'Room Tasks', room_tasks_path(@room) %>
</div>