config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: %i[show index]

  root 'rooms#index'

  patch '/user_tasks/:id', to: 'user_tasks#update', as: 'user_task'

  resources :rooms do
    resources :tasks, shallow: true do
      post '/user_tasks', to: 'user_tasks#create', as: 'volunteer'
      get '/user_tasks', to: 'user_tasks#new', as: 'help'
      delete '/user_tasks', to: 'user_tasks#destroy', as: 'cancel'
    end
  end

  get '/users/:id/tasks', to: 'tasks#index', as: 'users_tasks'
  get '/needs_help', to: 'needs_help#index'
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div id='user_navbar'>

  <% if user_signed_in? %>

  Logged in as <strong><%= current_user.email %></strong>

  <%= link_to 'Home', user_path(current_user) %> |
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> |
  <%= link_to 'Add Room', new_room_path %> |
  <%= link_to 'All Rooms', root_path %> |
  <%= link_to 'Needs Help', "/needs_help" %> |




  <% else %>

  <%= link_to 'Log In', new_user_session_path %> |
  <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %> |
  <%= link_to 'Sign Up', new_user_registration_path %>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PropertyForMarket</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>

  <%= render 'layouts/navbar' %>
  <%= yield %>


</body>


</html>